import { Router } from "express";
import { asyncHandler } from "../../core/utils/index.js";

function createReportsRoutes({
  controller,
  validation,
  validateRequest,
  requireAuth,
  authorize,
}) {
  const router = Router();

  router.get(
    "/filters/lead-options",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.leadFilterOptions),
    asyncHandler(controller.leadFilterOptions),
  );

  router.get(
    "/leads/by-source",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.bySource),
    asyncHandler(controller.leadsBySource),
  );
  router.get(
    "/leads/by-consultant",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.byConsultant),
    asyncHandler(controller.leadsByConsultant),
  );
  router.get(
    "/people/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.peoplePerformance),
    asyncHandler(controller.peoplePerformance),
  );
  router.get(
    "/quotations/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.quotationPerformance),
    asyncHandler(controller.quotationPerformance),
  );
  router.get(
    "/bookings/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.bookingPerformance),
    asyncHandler(controller.bookingPerformance),
  );
  router.get(
    "/finance/summary",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.financeSummary),
    asyncHandler(controller.financeSummary),
  );
  router.get(
    "/operations/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.operationsPerformance),
    asyncHandler(controller.operationsPerformance),
  );
  router.get(
    "/leads/deal-lines",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.dealLines),
    asyncHandler(controller.dealLines),
  );
  router.get(
    "/leads/aging",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.leadAging),
    asyncHandler(controller.leadAging),
  );
  router.get(
    "/leads/lost",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.lostLeads),
    asyncHandler(controller.lostLeads),
  );

  router.get(
    "/revenue/monthly",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.monthlyRevenue),
    asyncHandler(controller.revenueByMonth),
  );
  router.get(
    "/revenue/by-service-type",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.byServiceType),
    asyncHandler(controller.revenueByServiceType),
  );
  router.get(
    "/revenue/by-destination",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.byDestination),
    asyncHandler(controller.revenueByDestination),
  );

  router.get(
    "/sales/target-vs-achievement",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.targetVsAchievement),
    asyncHandler(controller.targetVsAchievement),
  );

  router.get(
    "/payments/outstanding",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.outstandingPayments),
    asyncHandler(controller.outstandingPayments),
  );
  router.get(
    "/payments/mode",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.paymentMode),
    asyncHandler(controller.paymentMode),
  );
  router.get(
    "/profit/margin",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.profitMargin),
    asyncHandler(controller.profitMargin),
  );
  router.get(
    "/finance/cost-breakup",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.financeCostBreakup),
    asyncHandler(controller.financeCostBreakup),
  );
  router.get(
    "/finance/supplier-services",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.financeSupplierServices),
    asyncHandler(controller.financeSupplierServices),
  );

  router.get(
    "/visa/summary",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.visaSummary),
    asyncHandler(controller.visaSummary),
  );

  router.get(
    "/followups/today",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.followupsToday),
    asyncHandler(controller.followupsToday),
  );
  router.get(
    "/followups/missed",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.followupsMissed),
    asyncHandler(controller.followupsMissed),
  );
  router.get(
    "/followups/call-log",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.callLog),
    asyncHandler(controller.callLog),
  );
  router.get(
    "/activities/feed",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.activityFeed),
    asyncHandler(controller.activityFeed),
  );

  router.get(
    "/monthly-summary",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.monthlySummary),
    asyncHandler(controller.monthlySummary),
  );
  router.get(
    "/dashboard/executive-kpis",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.executiveKpis),
    asyncHandler(controller.executiveKpis),
  );
  router.get(
    "/funnel/conversion",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.conversionFunnel),
    asyncHandler(controller.conversionFunnel),
  );
  router.get(
    "/marketing/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.marketingPerformance),
    asyncHandler(controller.marketingPerformance),
  );
  router.get(
    "/suppliers/performance",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.supplierPerformance),
    asyncHandler(controller.supplierPerformance),
  );
  router.get(
    "/forecast/pipeline",
    requireAuth,
    authorize("reports:read"),
    validateRequest(validation.pipelineForecast),
    asyncHandler(controller.pipelineForecast),
  );

  return router;
}

export { createReportsRoutes };
