const ROLE_PERMISSIONS = Object.freeze({
  super_admin: ['*'],
  admin: ['*'],
  manager: [
    'users:read',
    'leads:*',
    'quotations:*',
    'bookings:*',
    'customers:*',
    'campaigns:read',
    'visa:read',
    'payments:read',
    'refunds:read',
    'complaints:read',
    'reports:read',
  ],
  sales_consultant: [
    'leads:*',
    'quotations:*',
    'bookings:create',
    'bookings:read',
    'bookings:update',
    'customers:read',
    'visa:read',
    'complaints:create',
    'complaints:read',
  ],
  visa_executive: [
    'visa:*',
    'leads:read',
    'quotations:read',
    'bookings:read',
    'customers:read',
    'complaints:read',
  ],
  accounts: [
    'payments:*',
    'refunds:*',
    'bookings:read',
    'quotations:read',
    'customers:read',
    'reports:read',
  ],
  marketing: [
    'campaigns:*',
    'leads:read',
    'customers:read',
    'quotations:read',
    'reports:read',
  ],
  management: [
    'reports:read',
    'leads:read',
    'quotations:read',
    'bookings:read',
    'payments:read',
    'refunds:read',
    'visa:read',
    'campaigns:read',
    'customers:read',
    'complaints:read',
  ],

  // Backward-compatible aliases
  sales_manager: [
    'users:read',
    'leads:*',
    'quotations:*',
    'bookings:*',
    'customers:*',
    'campaigns:read',
    'visa:read',
    'payments:read',
    'refunds:read',
    'complaints:read',
    'reports:read',
  ],
  finance: ['payments:*', 'refunds:*', 'bookings:read', 'customers:read', 'reports:read'],
  support: ['complaints:*', 'customers:read', 'bookings:read'],
  agent: [
    'leads:*',
    'quotations:*',
    'bookings:create',
    'bookings:read',
    'bookings:update',
    'customers:read',
    'complaints:create',
    'complaints:read',
    'visa:read',
  ],
});

const DEFAULT_ROLE = 'sales_consultant';

module.exports = { ROLE_PERMISSIONS, DEFAULT_ROLE };
